### ISSUE TITLE
Off topic: The Heretic's Guide to Best Practices

### ISSUE THREAD

**Issue by ooker777** [nathan-artist/AppleScripts#3]
Hello, sorry for contacting you in this way. I see that in [this issue](https://github.com/christianvoigt/argdown/issues/129) over Argdown's repo you mention the book [The Heretic's Guide to Best Practices](https://books.google.com.vn/books?id=Gb2uuT1zrAAC&pg=PA169&redir_esc=y#v=onepage&q&f=false). I'm building an IBIS and belief system for my project myself, and I would be great if I can access this book. If you have an ebook of it, do you feel it fine to send it to me? Thank you so much for your time.

**Comment by nathan-artist** [comment]
@ooker777 I have the Kindle ebook but there is no way to share it. I don't know if you have access to Amazon.com in your country or what the pricing is like, but here in my country the ebook is inexpensive on Amazon.com and well worth the price. I recommend buying it if you can. I am going to close this issue but feel free to respond if you have any questions.
