### ISSUE TITLE
Still working in Monterey?

### ISSUE THREAD

**Issue by kenNash** [nathan-artist/AppleScripts#4]
Actually, I can't get "AppleScript applet for Spotlight URI handler" to work in macOS 12.4.

Ideas? Alternatives?

Thanks!

**Comment by nathan-artist** [comment]
Have you followed the instructions in the script, namely: saved the script as an applet, edited and saved the Info.plist file inside the applet to add the CFBundleURLTypes key, and then moved the applet to another location to register the URI with macOS Launch Services? If you have done all that on Monterey and it still doesn't work, there may be some kind of further macOS security permissions that you need to set; I heard that Apple tightened security for AppleScripts in more recent macOS versions. I'm not using Monterey yet so I can't test it.
